### ISSUE TITLE
[outreachy/gsoc] Interested in contributing

### ISSUE THREAD

**Issue by Vishnupriya1507** [huihut/interview#11]
I'm Vishnupriya Srivastava, from India.I am completing my graduation from Bits Pilani,India.I am a backend developer.I've done projects for my college using django framework,recently i worked with django channels creating a multichat gaming website.I know c and python and recently learning docker.
I would like to contribute to your project either by participating in outreachy or gsoc.
I read about this projects from last year's .

Please guide to on getting started.

**Comment by huihut** [comment]
Sorry, this is just my personal note, unlike other open source projects, and this repo was created this year. You can make an issue about the C++ interview, if you know Chinese. Otherwise I will think that you are a 水军.
![image](https://user-images.githubusercontent.com/23519480/44311128-58263400-a414-11e8-9cb0-b210f4052cbc.png)
